id: birth-event-rt-automation
name: Birth Event RT Automation
start: cron
steps:
  - id: create-birth-notifications
    name: Create birth notifications
    adaptor: '@openfn/language-opencrvs@1.1.1'
    configuration: taylor@openfn.org|OpenCRVS Demo 2026-05
    expression: ./create-birth-notifications.js
    next:
      send-back-tracking-ids:
        disabled: false
        condition: on_job_success
  - id: cron
    type: cron
    enabled: false
    cron_expression: '*/5 * * * *'
    next:
      get-teis-since-last-run:
        disabled: false
        condition: always
  - id: get-teis-since-last-run
    name: Get TEIs since last run
    adaptor: '@openfn/language-dhis2@8.0.12'
    configuration: taylor@openfn.org|DHIS2 Demo for BDR
    expression: ./get-teis-since-last-run.js
    next:
      transform-data:
        disabled: false
        condition: on_job_success
  - id: send-back-tracking-ids
    name: Send back tracking IDs
    adaptor: '@openfn/language-dhis2@8.0.12'
    configuration: taylor@openfn.org|DHIS2 Demo for BDR
    expression: ./send-back-tracking-ids.js
  - id: transform-data
    name: Transform data
    adaptor: '@openfn/language-common@3.3.1'
    expression: ./transform-data.js
    next:
      create-birth-notifications:
        disabled: false
        condition: on_job_success
